version: '3'
services:
  react-ui:
    build:
      context: ./frontend_orders
    ports:
      - '4000:4000'
    container_name: frontend_orders
    stdin_open: true
    volumes:
      - ./frontend_orders:/app_frontend_orders
      - /app_frontend_orders/node_modules
    networks:
      - test
  backend_artfx:
    build:
      context: ./backend_artfx/src/backend_artfx
    container_name: backend_artfx
    ports:
      - '5080:80'
    networks:
      - test
  nginx:
    build:
      context: ./backend_orders/nginx
    container_name: nginx_symfony
    volumes:
      - ./backend_orders/symfony:/var/www/symfony
    networks:
      - test
    ports:
      - '8080:8080'
  php:
    build:
      context: ./backend_orders/
      dockerfile: Dockerfile-php
    environment:
      APP_ENV: dev
    container_name: php_symfony
    volumes:
      - ./backend_orders/symfony:/var/www/symfony
    networks:
      - test
  mysql:
    image: mysql
    command:
      [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--default-authentication-plugin=mysql_native_password',
      ]
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - ./backend_orders/mysql:/var/lib/mysql
    networks:
      - test
networks:
  test:
    driver: bridge
